# fly.toml app configuration file generated for react-storefront on 2024-01-11T02:15:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-storefront"
primary_region = "cdg"

[build]

[env]
  NEXT_PUBLIC_SALEOR_API_URL = 'https://saleor.fly.dev/graphql/'
  NEXT_PUBLIC_STOREFRONT_URL = 'https://react-storefront.fly.dev'
  SITE_BACKGROUND = 'https://saleor-minio-nginx.fly.dev/saleor/pages/brown-satin-background-4k_ad56d38e.jpg?AWSAccessKeyId=saleoradmin&Signature=5KPKlQfu6wA1pk1X7nBRiJIz3Uw%3D&Expires=1711891582'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
